name: "Kubernetes end-to-end tests"
on: [push, pull_request]

jobs:
  end-to-end:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        TEST_GROUP: [smoke, es, cassandra, streaming, examples1, examples2, generate, es-otel, streaming-otel]
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.4'
    - uses: jpkrohling/setup-minikube@v1-release
      with:
        minikube-version: v1.12.1
    - uses: jpkrohling/setup-kubectl@v1-release
    - uses: jpkrohling/setup-operator-sdk@v1-release
      with:
        operator-sdk-version: v0.18.2
    - uses: actions/checkout@v1

    - name: "start minikube"
      run: ./.ci/start-minikube.sh

