name: "Kubernetes end-to-end tests"
on: [push, pull_request]

jobs:
  end-to-end:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - uses: jpkrohling/setup-minikube@v1-release
      with:
        minikube-version: v1.12.1

    - uses: jpkrohling/setup-kubectl@v1-release

    - name: "setup docker"
      run: ./.ci/setup-docker.sh

    - name: "start minikube"
      run: ./.ci/start-minikube.sh
